"""
Django settings for uderzoai project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from pathlib import Path
from django.core.management.utils import get_random_secret_key
import os
import sys
import dj_database_url
from decouple import config # decouple
from datetime import timedelta # simplejwt






# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECRET_KEY = 'django-insecure-$1h&%zwb6s)f%)hvdm*$#=6y#yc&src+!rhyi7e*vbpqkw$+*3'
# SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", get_random_secret_key())
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"
DEVELOPMENT_MODE = os.getenv("DEVELOPMENT_MODE", "False") == "True"
DOMAIN = os.getenv("DOMAIN", "fr8pro.app")
USE_SPACES = os.getenv("USE_SPACES") == "True"

# Email configs



EMAIL_BACKEND = config('EMAIL_BACKEND')
MAILER_EMAIL_BACKEND = config('MAILER_EMAIL_BACKEND')
EMAIL_HOST = config('EMAIL_HOST')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_PORT = config('EMAIL_PORT')
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL')

# Mapbox (public pk. token used client-side; injected into map templates via view context)
MAPBOX_ACCESS_TOKEN = config('MAPBOX_ACCESS_TOKEN', default='')

# REST FRAMEWORK Settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
        # 'uderzoai.permissions.UnauthenticatedPermission',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
}

# Simple JWT settings config Authorization JWT ->token
SIMPLE_JWT = {
    'AUTH_HEADER_TYPES': ('Bearer', 'JWT'),
    'ACCESS_TOKEN_LIFETIME': timedelta(days=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=14),
}

DJOSER = {
    'SERIALIZERS': {
        'user_create': 'core.serializers.UserCreateSerializer',
        'current_user': 'core.serializers.UserSerializer',
        'user': 'core.serializers.UserSerializer',
    },
    'USERNAME_RESET_CONFIRM_URL': 'auth/username/reset/confirm/{uid}/{token}',
    'SEND_ACTIVATION_EMAIL': True,
    #'ACTIVATION_URL': 'auth/activate/?uid={uid}&token={token}',
    'ACTIVATION_URL': 'accounts/activate/{uid}/{token}',
    'PASSWORD_RESET_CONFIRM_URL': 'auth/reset_password/?uid={uid}&token={token}',
    'PASSWORD_RESET_SHOW_EMAIL_NOT_FOUND': True,
    "LOGOUT_ON_PASSWORD_CHANGE": True,
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'ERROR',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}



SITE_NAME = 'FR8 Pro App'
if DEVELOPMENT_MODE:
    STORAGES = {
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
    }
elif USE_SPACES:
    # settings
    AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
    AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
    AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME")
    AWS_S3_ENDPOINT_URL = os.getenv("AWS_S3_ENDPOINT_URL")
    # AWS_LOCATION = os.getenv("AWS_LOCATION")
    AWS_S3_OBJECT_PARAMETERS = {'CacheControl': 'max-age-86400'}
    AWS_DEFAULT_ACL = 'public-read'
    AWS_S3_SIGNATURE_VERSION = 's3v4'
    AWS_MEDIA_LOCATION=os.getenv("AWS_LOCATION")
    PUBLIC_MEDIA_LOCATION=os.getenv("AWS_LOCATION")
    # MEDIA_URL =  'https://%s/%s/' % (AWS_S3_ENDPOINT_URL, AWS_MEDIA_LOCATION)
    MEDIA_URL = '%s/%s/' % (AWS_S3_ENDPOINT_URL, AWS_MEDIA_LOCATION)
    # MEDIA_ROOT = os.path.join(BASE_DIR, "media")
    
    STORAGES = {
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
        
        # "mediafiles": {
        #    "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        # },
        
        # "default": {
        #    "BACKEND": "django.core.files.storage.FileSystemStorage",
        # },
        "default": {"BACKEND": 'custom_storages.MediaStorage'},
        
        "OPTIONS": {
            "bucket_name": AWS_STORAGE_BUCKET_NAME,
            "signature_version": AWS_S3_SIGNATURE_VERSION,
            "signature_version": AWS_S3_SIGNATURE_VERSION,
        },
    
    }
    
else :   
    MEDIA_URL = '/media/'
    MEDIA_ROOT = os.path.join(BASE_DIR, "media")
    STORAGES = {
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
        
        "mediafiles": {
           "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
        },
        
        "default": {
           "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
    }
    

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static',] 

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles/")

 
# ALLOWED_HOSTS = ['*']
ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")

cors_domains = [
    f'http://{DOMAIN}',
    f'https://{DOMAIN}',
    f'http://www.{DOMAIN}',
    f'https://www.{DOMAIN}',
]

CORS_ALLOWED_ORIGINS = [
    'http://localhost:8000',
    'http://127.0.0.1',
    'https://127.0.0.1',
    'http://localhost',
    'https://localhost',
    'https://uderzo-ai-vmw4z.ondigitalocean.app',
    'https://www.uderzo.ai',
    'https://uderzo.ai',
    'https://www.therizz.app',
    'https://therizz.app',
    'https://www.fr8pro.app',
    'https://fr8pro.app',
    'https://www.fr8pro.ca',
    'https://fr8pro.ca',
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'http://localhost:3001',
    'http://localhost:5173',
    'http://169.254.173.71:3001',
    'https://fr8pro.ai',
    'https://www.fr8pro.ai',
]

if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True

CSRF_TRUSTED_ORIGINS = [
    'https://uderzo-ai-vmw4z.ondigitalocean.app',
    'https://fr8pro.app',
    'https://www.fr8pro.app',
    'https://fr8pro.ai',
    'https://www.fr8pro.ai',
]
# Allow extending via environment variables (comma separated)


# Robust parsing function to handle both commas and newlines
def parse_env_list(env_key, default=""):
    value = os.getenv(env_key, default)
    return [x.strip().strip("'").strip('"') for x in value.replace(',', '\n').splitlines() if x.strip()]

extra_cors_origins = parse_env_list("DJANGO_CORS_ALLOWED_ORIGINS")
extra_csrf_origins = parse_env_list("DJANGO_CSRF_TRUSTED_ORIGINS")

CORS_ALLOWED_ORIGINS.extend(cors_domains)
CORS_ALLOWED_ORIGINS.extend(extra_cors_origins)

CSRF_TRUSTED_ORIGINS.extend(cors_domains)
CSRF_TRUSTED_ORIGINS.extend(extra_csrf_origins)


# Application definition

INSTALLED_APPS = [
    'unfold',  # before django.contrib.admin
    'unfold.contrib.filters',  # optional, if special filters are needed
    # 'unfold.contrib.forms',  # optional, if special form elements are needed
    # 'unfold.contrib.import_export',  # optional, if django-import-export package is used
    # 'unfold.contrib.guardian',  # optional, if django-guardian package is used
    # 'unfold.contrib.simple_history',  # optional, if django-simple-history package is used
    'crispy_forms',
    'crispy_tailwind',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    "whitenoise.runserver_nostatic",
    'django.contrib.staticfiles',
    'core',
    'django_browser_reload',
    'storages',
    'django_extensions',
    'rest_framework',
    'djoser',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'ninja_extra',
    'django_tables2',
    'crudbuilder',
    'debug_toolbar',
]

# 
LOGIN_REQUIRED_FOR_CRUD = True
PERMISSION_REQUIRED_FOR_CRUD = False
PROJECT_NAME = 'uderzoai'

# crispy tailwind css settings
CRISPY_ALLOWED_TEMPLATE_PACKS = "tailwind"
CRISPY_TEMPLATE_PACK = "tailwind"

INTERNAL_IPS = [
    '127.0.0.1', 
]

# overwriting the auth user model to our own user model to enable customization
AUTH_USER_MODEL = 'core.CustomUser'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    "django_browser_reload.middleware.BrowserReloadMiddleware",
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# SESSION_ENGINE = "django.contrib.sessions.backends.cache" 
SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_AGE = 60*60*24
SESSION_COOKIE_SECURE = True

ROOT_URLCONF = 'uderzoai.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'uderzoai.wsgi.application'

if DEVELOPMENT_MODE is True:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": os.path.join(BASE_DIR, "db.sqlite3"),
        }
    }
elif len(sys.argv) > 0 and sys.argv[1] != 'collectstatic':
    if os.getenv("DATABASE_URL", None) is None:
        raise Exception("DATABASE_URL environment variable not defined")
    DATABASES = {
        "default": dj_database_url.parse(os.environ.get("DATABASE_URL")),
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

