# Generated by Django 4.2.4 on 2024-02-07 11:23

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_deactivated", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "address_line1",
                    models.CharField(
                        blank=True, max_length=45, verbose_name="Address line 1"
                    ),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True, max_length=45, verbose_name="Address line 2"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, verbose_name="Postal Code"
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=50)),
                (
                    "state_province",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="State/Province"
                    ),
                ),
                ("address_notes", models.CharField(blank=True, max_length=200)),
                (
                    "address_lat",
                    models.CharField(
                        blank=True, max_length=45, verbose_name="Address lat"
                    ),
                ),
                (
                    "address_lng",
                    models.CharField(
                        blank=True, max_length=45, verbose_name="Address lng"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "addresses",
            },
        ),
        migrations.CreateModel(
            name="Cat",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "cats",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("desc", models.CharField(max_length=200)),
                ("isfeatured", models.BooleanField(default=False)),
                ("isprivatelabel", models.BooleanField(default=False)),
                ("isactive", models.BooleanField(default=False)),
                (
                    "company_type",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "owner_operator"),
                            (2, "carrier"),
                            (3, "driver"),
                            (4, "shipper"),
                            (5, "merchant"),
                            (6, "vendor"),
                        ],
                        null=True,
                    ),
                ),
                ("upvotes", models.IntegerField(blank=True, default=0, null=True)),
                ("downvotes", models.IntegerField(blank=True, default=0, null=True)),
                ("cell_phone", models.CharField(max_length=200)),
                ("work_phone", models.CharField(max_length=200)),
                ("email", models.CharField(max_length=200)),
                ("website_url", models.CharField(max_length=200)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="uploads/"),
                ),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="uploads/"),
                ),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        default=0,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.address",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "companies",
            },
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "iso_code",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=45)),
            ],
            options={
                "verbose_name_plural": "Countries",
                "ordering": ["name", "iso_code"],
            },
        ),
        migrations.CreateModel(
            name="PropertyStatus",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name_plural": "propertystatus",
            },
        ),
        migrations.CreateModel(
            name="PropertyType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
            ],
            options={
                "verbose_name_plural": "propertytypes",
            },
        ),
        migrations.CreateModel(
            name="Stop",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("description", models.CharField(max_length=200)),
                (
                    "origin_address_full",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "destination_address_full",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "origin_window_range_start",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "destination_window_range_start",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "origin_tracking_number",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "load_number",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "manifest_number",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "destination_tracking_number",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="uploads/"),
                ),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="uploads/"),
                ),
                (
                    "proof_of_pickup_picture_1",
                    models.ImageField(blank=True, null=True, upload_to="uploads/"),
                ),
                (
                    "proof_of_delivery_picture_1",
                    models.ImageField(blank=True, null=True, upload_to="uploads/"),
                ),
                ("notes", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "contact_user",
                    models.ForeignKey(
                        blank=True,
                        default=1,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stop_contact_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination_address",
                    models.ForeignKey(
                        blank=True,
                        default=0,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stop_destination_address",
                        to="core.address",
                    ),
                ),
                (
                    "origin_address",
                    models.ForeignKey(
                        blank=True,
                        default=0,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stop_origin_address",
                        to="core.address",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "stops",
            },
        ),
        migrations.CreateModel(
            name="StateProvince",
            fields=[
                (
                    "iso_code",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=55)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.country"
                    ),
                ),
            ],
            options={
                "verbose_name": "State or province",
                "verbose_name_plural": "stateprovinces",
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="uploads/"),
                ),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="uploads/"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="core.category",
                    ),
                ),
                (
                    "created_user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="service_created_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="title"
                    ),
                ),
                ("notes", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "route_assigned_to_user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="route_assigned_to_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "stops",
                    models.ManyToManyField(
                        blank=True,
                        default=[0],
                        related_name="stops_in_this_route",
                        to="core.stop",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "routes",
            },
        ),
        migrations.CreateModel(
            name="Property",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("url", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True)),
                ("description", models.TextField()),
                ("fulladdress", models.TextField()),
                ("streetAddressLineOne", models.CharField(max_length=400)),
                ("streetAddressLineTwo", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=200)),
                ("state", models.CharField(max_length=200)),
                ("zipcode", models.CharField(max_length=200)),
                ("country", models.CharField(max_length=200)),
                ("latitude", models.CharField(max_length=200)),
                ("longitude", models.CharField(max_length=200)),
                ("zpid", models.CharField(max_length=200)),
                ("livingArea", models.CharField(max_length=200)),
                ("bathrooms", models.CharField(max_length=200)),
                ("bedrooms", models.CharField(max_length=200)),
                ("askingPrice", models.CharField(max_length=200)),
                ("propzPrice", models.CharField(max_length=200)),
                ("rentalMonthly", models.CharField(max_length=200)),
                ("image", models.ImageField(blank=True, upload_to="media/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                ("date_published", models.DateTimeField(auto_now_add=True)),
                ("isfavorite", models.BooleanField(default=False)),
                ("isfeatured", models.BooleanField(default=False)),
                (
                    "created_user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="property_created_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "propertyStatus",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.propertystatus",
                    ),
                ),
                (
                    "propertyType",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.propertytype",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "properties",
            },
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isactive", models.BooleanField(default=False)),
                ("userid", models.UUIDField(default=uuid.uuid4)),
                ("bio", models.TextField(blank=True, max_length=500)),
                ("birthdate", models.DateField(blank=True, null=True)),
                ("handle", models.CharField(blank=True, max_length=30)),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "role",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "regular"), (2, "admin"), (3, "god")],
                        null=True,
                    ),
                ),
                (
                    "thumb",
                    models.ImageField(
                        blank=True,
                        default="default.png",
                        null=True,
                        upload_to="uploads/",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "profiles",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="uploads/"),
                ),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="uploads/"),
                ),
                (
                    "cat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="core.cat",
                    ),
                ),
                (
                    "created_user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_created_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name"
                    ),
                ),
                (
                    "address_line1",
                    models.CharField(
                        blank=True,
                        max_length=45,
                        null=True,
                        verbose_name="Address line 1",
                    ),
                ),
                (
                    "address_line2",
                    models.CharField(
                        blank=True,
                        max_length=45,
                        null=True,
                        verbose_name="Address line 2",
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Postal Code"
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=50)),
                (
                    "state_province",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        verbose_name="State/Province",
                    ),
                ),
                ("address_notes", models.CharField(blank=True, max_length=200)),
                (
                    "address_lat",
                    models.CharField(
                        blank=True, max_length=45, null=True, verbose_name="Address lat"
                    ),
                ),
                (
                    "address_lng",
                    models.CharField(
                        blank=True, max_length=45, null=True, verbose_name="Address lng"
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.country",
                    ),
                ),
                (
                    "state_or_province",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.stateprovince",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="location_linked_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "locations",
                "unique_together": {
                    (
                        "address_line1",
                        "address_line2",
                        "postal_code",
                        "city",
                        "state_province",
                        "country",
                    )
                },
            },
        ),
        migrations.CreateModel(
            name="Load",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="uploads/"),
                ),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="uploads/"),
                ),
                (
                    "origin_tracking_number",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "load_number",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "manifest_number",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "destination_tracking_number",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("desc", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "origin_places_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "destination_places_id",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "origin_lat",
                    models.DecimalField(
                        blank=True, decimal_places=16, max_digits=22, null=True
                    ),
                ),
                (
                    "origin_lng",
                    models.DecimalField(
                        blank=True, decimal_places=16, max_digits=22, null=True
                    ),
                ),
                (
                    "destination_lat",
                    models.DecimalField(
                        blank=True, decimal_places=16, max_digits=22, null=True
                    ),
                ),
                (
                    "destination_lng",
                    models.DecimalField(
                        blank=True, decimal_places=16, max_digits=22, null=True
                    ),
                ),
                ("number_of_skids", models.IntegerField()),
                (
                    "origin_pickup_range_start",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "origin_pickup_range_end",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "destination_dropoff_range_start",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "destination_dropoff_range_end",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "origin_instructions",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("origin_is_appointment", models.BooleanField(default=False)),
                ("destination_is_appointment", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now_add=True)),
                (
                    "proof_of_pickup_picture_1",
                    models.ImageField(blank=True, null=True, upload_to="uploads/"),
                ),
                (
                    "proof_of_pickup_picture_2",
                    models.ImageField(blank=True, null=True, upload_to="uploads/"),
                ),
                (
                    "proof_of_pickup_picture_3",
                    models.ImageField(blank=True, null=True, upload_to="uploads/"),
                ),
                (
                    "proof_of_pickup_picture_4",
                    models.ImageField(blank=True, null=True, upload_to="uploads/"),
                ),
                (
                    "proof_of_pickup_picture_5",
                    models.ImageField(blank=True, null=True, upload_to="uploads/"),
                ),
                (
                    "proof_of_delivery_picture_1",
                    models.ImageField(blank=True, null=True, upload_to="uploads/"),
                ),
                (
                    "proof_of_delivery_picture_2",
                    models.ImageField(blank=True, null=True, upload_to="uploads/"),
                ),
                (
                    "proof_of_delivery_picture_3",
                    models.ImageField(blank=True, null=True, upload_to="uploads/"),
                ),
                (
                    "proof_of_delivery_picture_4",
                    models.ImageField(blank=True, null=True, upload_to="uploads/"),
                ),
                (
                    "proof_of_delivery_picture_5",
                    models.ImageField(blank=True, null=True, upload_to="uploads/"),
                ),
                ("notes", models.CharField(blank=True, max_length=200, null=True)),
                ("load_assigned_at", models.DateTimeField(blank=True, null=True)),
                ("load_started_at", models.DateTimeField(blank=True, null=True)),
                ("load_completion_at", models.DateTimeField(blank=True, null=True)),
                ("is_test_data", models.BooleanField(default=True)),
                (
                    "destination_company",
                    models.ForeignKey(
                        blank=True,
                        default=0,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="load_to_company",
                        to="core.company",
                    ),
                ),
                (
                    "destination_user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="load_user_destination",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "dropoff_address",
                    models.ForeignKey(
                        blank=True,
                        default=0,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="to_address",
                        to="core.address",
                    ),
                ),
                (
                    "load_assigned_by_user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="load_assigned_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "load_assigned_to_user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="load_assigned_to_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "load_created_by_user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="load_created_by_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "origin_address",
                    models.ForeignKey(
                        blank=True,
                        default=0,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="from_address",
                        to="core.address",
                    ),
                ),
                (
                    "origin_company",
                    models.ForeignKey(
                        blank=True,
                        default=0,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="load_from_company",
                        to="core.company",
                    ),
                ),
                (
                    "origin_user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="load_user_origin",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "loads",
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.location",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "devices",
            },
        ),
        migrations.CreateModel(
            name="Dataset",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField()),
                ("description", models.TextField(blank=True, null=True)),
                ("price", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="uploads/"),
                ),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="uploads/"),
                ),
                (
                    "created_user",
                    models.ForeignKey(
                        default=1,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="dataset_created_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.AddField(
            model_name="address",
            name="country",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.country",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="state_or_province",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.stateprovince",
            ),
        ),
        migrations.AddField(
            model_name="address",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="address_linked_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="address",
            unique_together={
                (
                    "address_line1",
                    "address_line2",
                    "postal_code",
                    "city",
                    "state_province",
                    "country",
                )
            },
        ),
    ]
