# Generated by Django 4.2.4 on 2024-02-09 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_stop_contact_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stop",
            name="contact_user",
            field=models.ForeignKey(
                blank=True,
                default=1,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stop_contact_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
