# Generated by Django 4.2.4 on 2024-02-09 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_stop_contact_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stop",
            name="destination_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stop_destination_address",
                to="core.address",
            ),
        ),
        migrations.AlterField(
            model_name="stop",
            name="origin_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stop_origin_address",
                to="core.address",
            ),
        ),
    ]
