# Generated by Django 4.2.4 on 2024-02-10 00:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_alter_route_route_assigned_to_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="route",
            name="route_assigned_to_user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="route_assigned_to_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
