# Generated by Django 4.2.4 on 2024-02-10 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_route_route_assigned_to_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="address_lat",
            field=models.CharField(
                blank=True, max_length=45, null=True, verbose_name="Address lat"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="address_lng",
            field=models.CharField(
                blank=True, max_length=45, null=True, verbose_name="Address lng"
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.country",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="state_or_province",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.stateprovince",
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="address_linked_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
