# Generated by Django 4.2.4 on 2024-02-11 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_address_address_lat_alter_address_address_lng_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="stop",
            name="destination_notes",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="stop",
            name="origin_notes",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
