# Generated by Django 4.2.4 on 2024-02-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_stop_destination_notes_stop_origin_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="stop",
            name="ordering_number",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
