# Generated by Django 4.2.4 on 2024-02-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_stop_ordering_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="EVChargingLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_name", models.CharField(max_length=250)),
                ("station_address", models.CharField(max_length=250)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
    ]
