# Generated by Django 4.2.4 on 2024-02-12 09:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_evcharginglocation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="evcharginglocation",
            options={"verbose_name_plural": "evcharginglocations"},
        ),
    ]
