# Generated by Django 4.2.4 on 2025-12-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_evcharginglocation_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="capacity",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="license_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="truck_type",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
