# Generated by Django 4.2.4 on 2025-12-08 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_blacklistedaccesstoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employees",
                to="core.company",
            ),
        ),
    ]
