# Generated by Django 4.2.4 on 2025-12-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_profile_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="load",
            name="value",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0.0, max_digits=10, null=True
            ),
        ),
    ]
