# Generated by Django 4.2.4 on 2025-12-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0016_load_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="load",
            name="destination_instructions",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
