# Generated by Django 4.2.4 on 2026-02-09 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_load_destination_instructions"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="base_location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("active", "Active"),
                    ("rest", "Rest"),
                    ("off_duty", "Off Duty"),
                ],
                default="active",
                max_length=10,
            ),
        ),
    ]
